### ISSUE TITLE
Surplus to requirements

### ISSUE THREAD

**Issue by mrnil** [dwpdigitaltech/govlist#1]
If this is a list of public repos for which there is a list that already exists and is more complete, surely this repo and it's list is surplus to requirements? All you're doing is creating duplicated and increasingly out of date information.

**Comment by ivernus** [comment]
This is a cut down version of central government URLs rather than the exhaustive on on the github government pages. It can also have other non github URLs added as people please. Its designed to be a very simple easily browsable list rather than the expansive graphics filled version of the github government also.

**Comment by mrnil** [comment]
Nope. Still don't get it why you're duplicating an existing resource. Worse you appear to be suggesting that this would be a random set of links. 

What's the perceived user need that you're fulfilling here? Is this actually just your own personal github hosted bookmark page? If that's all it is, can I suggest you either use Google bookmarks which will be available on all your devices or move this to your personal github space.

**Comment by ivernus** [comment]
The user need is focused around simplicity, the links found on the existing list are available on a graphics heavy list with lots of surplus information. This would not be a random set of links, this would be a curated list of links to central government version control repositories and not based solely on one popular version control site. 

Another good example of this is the awesome lists on github which I'm sure you are aware of. If you feel more comfortable Ill move it to my own repo though. I will give you a call tomorrow and see if you can advise on some of the requirements that lead to this list being created.
